-- Bring the repo in line with production: this index EXISTS live and is created by no migration
-- in this tree.
--
-- Verified against production 2026-08-01:
--   CREATE UNIQUE INDEX idx_users_orcid ON users(orcid_id) WHERE orcid_id IS NOT NULL AND orcid_id != ''
--
-- It is the only thing preventing two accounts from claiming one ORCID iD. handleRegister checks
-- for a duplicate with a SELECT and then INSERTs, which is a read-then-write: two registrations
-- carrying the same verified iD can both pass the SELECT before either INSERT lands, and the
-- database is what actually settles it. That makes this index load-bearing, not an optimisation
-- — and a rebuild from this repo would have silently produced a schema without it, leaving the
-- check as advisory and letting the duplicate through.
--
-- Partial (WHERE orcid_id IS NOT NULL AND orcid_id != '') because most rows have no ORCID iD at
-- all, and a plain UNIQUE index would treat every empty string as a collision — blocking every
-- registration after the first. That is presumably why it was written this way live, and it is
-- why this file reproduces the predicate exactly rather than "tidying" it.
--
-- IF NOT EXISTS so applying this to production is a no-op and applying it to a fresh database
-- gets the constraint. Verified before writing: 0 rows would violate it.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_orcid
  ON users(orcid_id) WHERE orcid_id IS NOT NULL AND orcid_id != '';
